#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

yarn lint-staged

# If everything passes... Now we can commit
echo '✅✅✅✅ Success passed a configuration... I am committing this now. ✅✅✅✅'
